name: Deploy

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mdBook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.51/mdbook-v0.4.51-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin

      - name: Build Docs
        run: bin/mdbook build

      - name: Configure environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "CLOUDFLARE_ENV=production" >> $GITHUB_ENV
          else
            echo "CLOUDFLARE_ENV=development" >> $GITHUB_ENV
          fi

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: ${{ env.CLOUDFLARE_ENV }}
